import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

// import Amplify from 'aws-amplify';
// import aws_exports from './aws-exports';
// Amplify.configure(aws_exports);

// import the modules
import Amplify from '@aws-amplify/core';
// import Auth from '@aws-amplify/auth';
import API from '@aws-amplify/api';
import Storage from '@aws-amplify/storage';

// import the config file that's generated by the CLI
import AWSConfig from './aws-exports';

// configure amplify with it
Amplify.configure(AWSConfig);
// Auth.configure(AWSConfig);
API.configure(AWSConfig);
Storage.configure(AWSConfig);

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
